site_name: echoes
extra_css:
  - custom.css

repo_url: https://github.com/fabridamicelli/echoes
site_url: https://fabridamicelli.github.io/echoes/
site_description: Echo State Networks in Python
site_author: Fabrizio Damicelli

nav:
  - Home: index.md
  - What are Echo State Networks?: tutorial/index.md
  - Examples:
    - ESNRegressor (sin-cos): examples/notebooks/plot_regressor_sincos.ipynb
    - ESNGenerator (Mackey-Glass): examples/notebooks/plot_generator_mackeyglass17.ipynb 
    - Plot Reservoir Activity: examples/notebooks/plot_reservoir_activity.ipynb
    - ESNRegressor GridSearchCV: examples/notebooks/plot_regressor-gridsearch.ipynb
    - ESNRegressor, GridSearchCV, Pipeline: examples/notebooks/plot_regressor-pipeline-and-gridsearch.ipynb
  - API:
    - ESNRegressor: api/ESNRegressor.md
    - ESNGenerator: api/ESNGenerator.md
    - plotting: api/plotting.md
    - utils: api/utils.md

theme:
  name: material
  custom_dir: theme/
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - toc:
      permalink: true
  - codehilite

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
  - mkdocs-jupyter:
      execute: false
      # include: ["*.ipynb", "examples/notebooks/*.ipynb"]
      # ignore: ["some-irrelevant-files/*.ipynb"]


copyright: Copyright &copy; 2020 Maintained by <a href="https://twitter.com/fabridamicelli">Fabrizio</a>.

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fabridamicelli
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fabridamicelli
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/fabridamicelli
